### ISSUE TITLE
[wishlist] Number of icon size (or columns) control

### ISSUE THREAD

**Issue by cibersheep** [bhdouglass/falcon#4]
It is very nice that icon size adapts to screen size but it would be possible to control the number of icons columns that is displayed? Or the maximum size of the icon?

The idea would be have a bit of control in how many apps are displayed.

**Comment by bhdouglass** [comment]
Unfortunately there is a limited amount of control over the size of the icons (they can't get any smaller), but I can see about alternative layouts/larger sizes.

**Comment by bhdouglass** [comment]
I've added support for changing the size and layout of the icons. Although making the icons any bigger that "small" seems kinda silly.
