### ISSUE TITLE
M10 update didn't work well

### ISSUE THREAD

**Issue by cibersheep** [bhdouglass/falcon#5]
Updating was not fruitful on m10.
Update seemed to go well but theme was lost and not able to install it again.
Tried to uninstall, reboot install again. That made new features to work (icon size, display options) except for hide apps.
Tried to delte config ini and app folder from .local, no difference.

**Comment by cibersheep** [comment]
![screenshot20170202_113004252](https://cloud.githubusercontent.com/assets/6640041/22553979/d725fdca-e95e-11e6-8fff-f4328defe9a8.png)
![screenshot20170202_113401633](https://cloud.githubusercontent.com/assets/6640041/22553980/d73b4d42-e95e-11e6-83a6-754a836d8167.png)

**Comment by bhdouglass** [comment]
Did you try with v2.01? That should fix the icon pack display issue. Due to how scopes work, you probably needed to "exit" the scope and restart it to get the updated settings (no hiding apps yet, maybe next release!).

**Comment by cibersheep** [comment]
Uuuuuiiiiii... I confirm: 2.01 fixes this. Thank you.
And sorry, I understood 'hidden apps' was also in this release.... No pressure ☺😉

**Comment by bhdouglass** [comment]
hahaha, no pressure at all :D
