### ISSUE TITLE
[wishlist] More icon size setting

### ISSUE THREAD

**Issue by tomvicik** [bhdouglass/falcon#6]
Falcon scope is great idea! I've just installed open store and I'm exciting about Falcon. But honestly I prefer smaller icons (just like the ones in default apps scope). Is it able to add the option?

**Comment by bhdouglass** [comment]
I'm glad you like it :) Unfortunately I've set the icons as small as they can go. The normal app scope uses a hack to get it's icons smaller. I've filed a bug upstream for this: https://bugs.launchpad.net/ubuntu-ux/+bug/1490388
