### ISSUE TITLE
Ubuntu store is listed on ubports ut device

### ISSUE THREAD

**Issue by YougoCodes** [bhdouglass/falcon#7]
Device: Fairphone 2
Os: Ubports Ubuntu touch devel r273
Falcon version: 2.02
Icon pack: None active 

The Ubuntu store has been removed by ubports team, but is still listed as a scope in falcon. There is no icon, and clicking it does nothing. refreshing falcon does nothing.

Should it be removed in falcon, or should ubports team clean up something? Or does the user need to clear some cache ( which one)?

**Comment by bhdouglass** [comment]
This'll have to be removed in falcon, I'll see about pushing an update to the OpenStore soon.

**Comment by YougoCodes** [comment]
Thanks in advance. Perhaps it is good to consider adding some check, should someone be running falcon on a Canonical UT install, and still need to be able to launch the ubuntu Store. (for as long as it still has a server...)

**Comment by bhdouglass** [comment]
Fixed this in v2.03! I opted to just completely remove it rather than checking since the store will be shutdown soon anyways.
